### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by fonko** [ezekg/sitepoint-programmatically-insert-wp-posts#1]
When trying to test the first part of this code (the one that lists all posts) i get "Oops! That page can’t be found." because when i click the button it goes to http://clodagh.staging.wpengine.com/wp-admin/&insert_sitepoint_posts.

not sure if this is an general issue or if i didn't understood the code.

pls help  ! :)

**Comment by ezekg** [comment]
It looks like [this line](https://github.com/ezekg/sitepoint-programmatically-insert-wp-posts/blob/master/create-posts-from-csv.php?ts=2#L10) needs to account for the fact that the URL may not always have `?` in it (i.e. there are no query params, which were always present at the time of writing this article).

To fix it: instead of `&insert_sitepoint_posts`, it should append `?insert_sitepoint_posts` if the `$_SERVER['REQUEST_URI']` variable doesn't contain any query params i.e. `?`.

Does that make sense?

**Comment by fonko** [comment]
yes, it does. Thanks!

**Comment by ezekg** [comment]
Sweet. 🖖
